### ISSUE TITLE
Bug: Friend delete button crash.

### ISSUE THREAD

**Issue by jenyangk** [CMPUT301F19T19/legendary-fiesta#84]

**Comment by liushuyu** [comment]
Cannot reproduce the issue often

**Comment by jenyangk** [comment]
Crash causes app to partially send a FireBase request.

**Comment by jenyangk** [comment]
I have found the issue:

I believe this issue is caused when you press delete multiple times and the app registers the multiple delete button clicks and attempts to delete the same thing multiple times (both from the array and FireBase).


OUTPUT:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.cmput301f19t19.legendary_fiesta, PID: 4980
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.remove(ArrayList.java:503)
        at io.github.cmput301f19t19.legendary_fiesta.ui.FriendsFragment$3.onSuccess(FriendsFragment.java:125)
        at io.github.cmput301f19t19.legendary_fiesta.ui.FriendsFragment$3.onSuccess(FriendsFragment.java:122)
        at io.github.cmput301f19t19.legendary_fiesta.-$$Lambda$_npTaM7Ux7pvX4S3tVtiJyiyLlA.onSuccess(Unknown Source:4)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
